### ISSUE TITLE
Plugin doesn't create "uploads" folder

### ISSUE THREAD

**Issue by 11x11alex** [iamgreggarcia/codesherpa#13]
+ doesn't see any files if I create the "uploads" folder manually

what could be the issue? I'm running a Apple M2 chip MacBook, and I think Docker is a bit weird about it...

**Comment by iamgreggarcia** [comment]
Hi @11x11alex, 

I've added a simple upload form that can be accessed by:

- navigating to  http://localhost:3333/upload, or
- telling ChatGPT you want to upload a file, after which it will embed a hyperlink it the response taking you to the same /upload url: 
![upload-demo](https://github.com/iamgreggarcia/codesherpa/assets/16596972/0a631394-4c1b-465d-8e70-da3b1d58499e)

This allows you to directly upload files to the running Docker container on your machine (Apple silicon/M2 or otherwise).

You can download the latest image [here](https://github.com/iamgreggarcia/codesherpa/pkgs/container/codesherpa/97824807?tag=latest) or run
```bash
docker pull ghcr.io/iamgreggarcia/codesherpa:latest
```
from your command line. 

Let me know if that works!

**Comment by 11x11alex** [comment]
Awesome. I'll check it out soon and I'll confirm if it works. I've sent you an email, did you get it? Would love to get in touch with you
